# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoteLand' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NoteLand

  pod 'RealmSwift', '=10.1.4'


  target 'NoteLandTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoteLandUITests' do
    # Pods for testing
  end

end
